# Используем базовый образ Python
FROM python:3.10-slim

# Устанавливаем рабочую директорию
WORKDIR /auth

# Копируем файл зависимостей
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем auth.py из корневой директории
COPY auth.py .

# Указываем порт, который будет использовать приложение
EXPOSE 8000

# Команда для запуска сервера
CMD ["uvicorn", "auth:app", "--host", "0.0.0.0", "--port", "8000"]
