version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - web
    networks:
      - app-network
    volumes:
      - ./bots:/bot
    environment:
      - FASTAPI_URL=http://web:8000
      - PYTHONUNBUFFERED=1

networks:
  app-network:
    driver: bridge